name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: CI Job
    # This job runs on Linux
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: "[15.9]"
    - name: echo msbuild path
      run: echo "${{ steps.setup_msbuild.outputs.msbuildPath }}"

    - name: echo MSBuild
      run: msbuild -version
    # This step prints an output (time) from the previous step's action.
    - name: Setup NuGet
      run: NuGet/setup-nuget@v1.0.2
    # This step prints an output (time) from the previous step's action.
    - name: Restore NuGet Packages
      run: nuget restore Ejercicios.sln
    # This step prints an output (time) from the previous step's action.
    - name: Build and Publish Web App
      run: msbuild Ejercicios.sln
